spring.application.name=spring_react_postg
spring.datasource.url=jdbc:postgresql://localhost:5432/flashcards
spring.datasource.username=postgres
spring.datasource.password=123

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring_react_postg.app.jwtSecret= spring_react_postg
spring_react_postg.app.jwtExpirationMs=86400000


management.endpoints.web.exposure.include=health,info,metrics,env,beans,httptrace
management.endpoint.metrics.enabled=true
management.endpoint.health.show-details=always





